using System.Data.Common;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.Rendering;

public class Projectile : MonoBehaviour
{
    [Header("Projectiles info")]
    public float SpeedOfProjectile;
    public float LifeTimeOfProjectile;
    public float DistanceOfProjectile;

    [Header("Enemy Ref")]
    public GameObject EnemyArcherGO;

    [Header("Layers")]
    public LayerMask Enemy;
    private void Start()
    {
        Invoke("DestroyProjectile", LifeTimeOfProjectile);
    }


    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.CompareTag("Player"))
        {
            Debug.Log("hit player");
            NPCController.Instance.Player.GetComponent<BaseCharacter>().TakeDamage(EnemyArcherGO.GetComponent<EnemyArcher>().EnemyDamage);
            DestroyProjectile();
        }
        else if(collision.CompareTag("Enemy"))
        {
            Debug.Log("hit enemy");
            collision.gameObject.GetComponent<BaseEnemy>().TakeDamage(NPCController.Instance.Player.gameObject.GetComponent<PlayerInfo>().RangeDamg);
            DestroyProjectile();
        }
   
    }
    private void Update()
    {
        /*
        RaycastHit2D hitinfo = Physics2D.Raycast(transform.position, transform.up, DistanceOfProjectile, Enemy);
        if(hitinfo.collider != null)
        {
            if (hitinfo)
            {
                if (hitinfo.collider.gameObject.GetComponent<BaseCharacter>() != null)
                {
                    hitinfo.collider.GetComponent<BaseCharacter>().TakeDamage(RangeDamage);
                }
                else if (hitinfo.collider.gameObject.GetComponent<BaseEnemy>() != null)
                {
                    Debug.Log("loook");
                    hitinfo.collider.GetComponent<BaseEnemy>().TakeDamage(RangeDamage);
                }
                else if (hitinfo.collider.gameObject.CompareTag("Barricade"))
                {
                    Debug.Log("u hit barricade");
                    BarricadeController.Instance.BarricadeTakesDamage(RangeDamage);
                }
                else if (hitinfo.collider.gameObject.CompareTag("Shield"))
                {
                    Debug.Log("hit sheild!");
                }
            }

        }
        else
        {
            Debug.Log("U hit nothinmg");
            //DestroyProjectile();
        }
        */
            transform.Translate(Vector2.up * SpeedOfProjectile * Time.deltaTime);
    }

    void DestroyProjectile()
    {
        Destroy(gameObject);
    }
}
